CREATE TABLE IF NOT EXISTS sources (
    source_id INTEGER PRIMARY KEY AUTOINCREMENT,
    source_key TEXT NOT NULL UNIQUE,
    source_type TEXT NOT NULL,
    display_name TEXT NOT NULL,
    normalized_value TEXT NOT NULL,
    url TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    date_added TEXT NOT NULL,
    notes TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS analysis_runs (
    analysis_run_id TEXT PRIMARY KEY,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    status TEXT NOT NULL,
    data_mode TEXT NOT NULL,
    run_type TEXT NOT NULL DEFAULT 'discovery',
    canonical_trend_run INTEGER NOT NULL DEFAULT 0,
    selected_source_ids TEXT NOT NULL,
    time_window_label TEXT NOT NULL,
    time_window_start TEXT NOT NULL,
    time_window_end TEXT NOT NULL,
    max_posts_per_source INTEGER NOT NULL,
    max_comments_per_thread INTEGER NOT NULL,
    include_comments INTEGER NOT NULL,
    run_deeper_analysis INTEGER NOT NULL,
    ollama_model TEXT NOT NULL,
    ollama_url TEXT NOT NULL,
    summary_json TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS scrape_source_coverage (
    analysis_run_id TEXT NOT NULL,
    source_id INTEGER,
    source_name TEXT NOT NULL,
    source_type TEXT NOT NULL,
    scrape_mode TEXT NOT NULL,
    lookback_hours REAL NOT NULL,
    posts_requested INTEGER NOT NULL,
    posts_returned INTEGER NOT NULL,
    comments_requested INTEGER NOT NULL,
    comments_returned INTEGER NOT NULL,
    threads_returned INTEGER NOT NULL,
    authors_returned INTEGER NOT NULL,
    oldest_seen_at TEXT NOT NULL,
    newest_seen_at TEXT NOT NULL,
    hit_post_cap INTEGER NOT NULL DEFAULT 0,
    hit_rss_cap INTEGER NOT NULL DEFAULT 0,
    rate_limited INTEGER NOT NULL DEFAULT 0,
    collection_error TEXT NOT NULL DEFAULT '',
    collection_completed INTEGER NOT NULL DEFAULT 1,
    canonical_trend_run INTEGER NOT NULL DEFAULT 0,
    coverage_reliability REAL NOT NULL DEFAULT 0,
    reliability_label TEXT NOT NULL DEFAULT 'Low',
    reliability_reason_json TEXT NOT NULL DEFAULT '[]',
    PRIMARY KEY (analysis_run_id, source_id),
    FOREIGN KEY (analysis_run_id) REFERENCES analysis_runs(analysis_run_id),
    FOREIGN KEY (source_id) REFERENCES sources(source_id)
);

CREATE TABLE IF NOT EXISTS reddit_items (
    item_id TEXT PRIMARY KEY,
    source_id INTEGER,
    source_type TEXT NOT NULL,
    source_name TEXT NOT NULL,
    subreddit TEXT,
    thread_id TEXT NOT NULL,
    thread_title TEXT NOT NULL,
    thread_url TEXT NOT NULL,
    comment_id TEXT,
    parent_id TEXT,
    item_type TEXT NOT NULL,
    body_text TEXT NOT NULL,
    author TEXT NOT NULL,
    author_hash TEXT NOT NULL,
    score INTEGER NOT NULL,
    created_time TEXT NOT NULL,
    permalink TEXT NOT NULL,
    comment_depth INTEGER NOT NULL,
    raw_json TEXT NOT NULL,
    FOREIGN KEY (source_id) REFERENCES sources(source_id)
);

CREATE TABLE IF NOT EXISTS classifications (
    analysis_run_id TEXT NOT NULL,
    item_id TEXT NOT NULL,
    sentiment TEXT NOT NULL,
    confidence REAL NOT NULL,
    tickers TEXT NOT NULL,
    company_names TEXT NOT NULL,
    summary TEXT NOT NULL,
    bull_case TEXT NOT NULL,
    bear_case TEXT NOT NULL,
    evidence_quality TEXT NOT NULL,
    depth_score INTEGER NOT NULL,
    hype_score INTEGER NOT NULL,
    claim_specificity_score INTEGER NOT NULL,
    repetition_score INTEGER NOT NULL,
    needs_deeper_analysis INTEGER NOT NULL,
    red_flags TEXT NOT NULL,
    claims_to_verify TEXT NOT NULL,
    alpha_signal_score REAL NOT NULL,
    hype_adjusted_signal_score REAL NOT NULL,
    model_name TEXT NOT NULL,
    classifier_mode TEXT NOT NULL,
    deeper_analysis_json TEXT NOT NULL DEFAULT '{}',
    analyzed_at TEXT NOT NULL,
    PRIMARY KEY (analysis_run_id, item_id),
    FOREIGN KEY (analysis_run_id) REFERENCES analysis_runs(analysis_run_id),
    FOREIGN KEY (item_id) REFERENCES reddit_items(item_id)
);

CREATE TABLE IF NOT EXISTS item_ticker_mentions (
    analysis_run_id TEXT NOT NULL,
    item_id TEXT NOT NULL,
    source_id INTEGER,
    source_type TEXT NOT NULL,
    source_name TEXT NOT NULL,
    subreddit TEXT,
    thread_id TEXT NOT NULL,
    thread_title TEXT NOT NULL,
    comment_id TEXT,
    parent_id TEXT,
    author_hash TEXT NOT NULL,
    created_time TEXT NOT NULL,
    created_date TEXT NOT NULL,
    time_bucket TEXT NOT NULL,
    item_type TEXT NOT NULL,
    ticker TEXT NOT NULL,
    company_name TEXT NOT NULL,
    sentiment TEXT NOT NULL,
    sentiment_numeric REAL,
    confidence REAL NOT NULL,
    alpha_signal_score REAL NOT NULL,
    hype_adjusted_signal_score REAL NOT NULL,
    depth_score INTEGER NOT NULL,
    hype_score INTEGER NOT NULL,
    evidence_quality TEXT NOT NULL,
    evidence_quality_numeric INTEGER NOT NULL,
    claim_specificity_score INTEGER NOT NULL,
    source_diversity_score REAL NOT NULL,
    controversy_score REAL NOT NULL,
    repetition_score INTEGER NOT NULL,
    reddit_score INTEGER NOT NULL,
    comment_depth INTEGER NOT NULL,
    text_length INTEGER NOT NULL,
    word_count INTEGER NOT NULL,
    contains_link INTEGER NOT NULL,
    contains_numbers INTEGER NOT NULL,
    contains_financial_terms INTEGER NOT NULL,
    needs_deeper_analysis INTEGER NOT NULL,
    low_mentions_high_signal INTEGER NOT NULL,
    new_ticker_detected INTEGER NOT NULL,
    red_flag_count INTEGER NOT NULL,
    claims_to_verify TEXT NOT NULL,
    summary TEXT NOT NULL,
    bull_case TEXT NOT NULL,
    bear_case TEXT NOT NULL,
    red_flags TEXT NOT NULL,
    deeper_analysis_json TEXT NOT NULL,
    body_text TEXT NOT NULL,
    permalink TEXT NOT NULL,
    PRIMARY KEY (analysis_run_id, item_id, ticker),
    FOREIGN KEY (analysis_run_id) REFERENCES analysis_runs(analysis_run_id),
    FOREIGN KEY (item_id) REFERENCES reddit_items(item_id),
    FOREIGN KEY (source_id) REFERENCES sources(source_id)
);

CREATE TABLE IF NOT EXISTS ticker_summaries (
    analysis_run_id TEXT NOT NULL,
    ticker TEXT NOT NULL,
    company_name TEXT NOT NULL,
    total_mentions INTEGER NOT NULL,
    bullish_mentions INTEGER NOT NULL,
    bearish_mentions INTEGER NOT NULL,
    neutral_mentions INTEGER NOT NULL,
    bullish_ratio REAL NOT NULL,
    bearish_ratio REAL NOT NULL,
    net_sentiment_score REAL,
    average_confidence REAL NOT NULL,
    average_alpha_signal_score REAL NOT NULL,
    average_hype_adjusted_signal_score REAL NOT NULL,
    average_depth_score REAL NOT NULL,
    average_hype_score REAL NOT NULL,
    average_claim_specificity_score REAL NOT NULL,
    average_evidence_quality_numeric REAL NOT NULL,
    source_diversity_score REAL NOT NULL,
    controversy_score REAL NOT NULL,
    repetition_score REAL NOT NULL,
    unique_authors INTEGER NOT NULL,
    unique_threads INTEGER NOT NULL,
    first_seen_date TEXT NOT NULL,
    most_recent_seen_date TEXT NOT NULL,
    mentions_this_period INTEGER NOT NULL,
    mentions_previous_period INTEGER NOT NULL,
    mention_change INTEGER NOT NULL,
    mention_growth_rate REAL,
    bullish_change INTEGER NOT NULL,
    bullish_growth_rate REAL,
    unique_author_growth INTEGER NOT NULL,
    unique_thread_growth INTEGER NOT NULL,
    rolling_mention_average REAL NOT NULL,
    acceleration_score REAL NOT NULL,
    coverage_adjusted_acceleration_score REAL NOT NULL DEFAULT 0,
    mention_rate_per_100_posts REAL NOT NULL DEFAULT 0,
    thread_rate_per_100_posts REAL NOT NULL DEFAULT 0,
    author_rate_per_100_posts REAL NOT NULL DEFAULT 0,
    coverage_reliability REAL NOT NULL DEFAULT 0,
    trend_reliability TEXT NOT NULL DEFAULT 'Legacy',
    trend_reliability_reason TEXT NOT NULL DEFAULT '',
    matched_source_count INTEGER NOT NULL DEFAULT 0,
    total_posts_scraped INTEGER NOT NULL DEFAULT 0,
    previous_posts_scraped INTEGER NOT NULL DEFAULT 0,
    emerging_ticker_score REAL NOT NULL,
    low_mentions_high_signal INTEGER NOT NULL,
    new_ticker_detected INTEGER NOT NULL,
    mega_popularity_penalty REAL NOT NULL,
    PRIMARY KEY (analysis_run_id, ticker),
    FOREIGN KEY (analysis_run_id) REFERENCES analysis_runs(analysis_run_id)
);

CREATE TABLE IF NOT EXISTS ticker_time_buckets (
    analysis_run_id TEXT NOT NULL,
    ticker TEXT NOT NULL,
    company_name TEXT NOT NULL,
    time_bucket TEXT NOT NULL,
    bucket_start TEXT NOT NULL,
    bucket_end TEXT NOT NULL,
    total_mentions INTEGER NOT NULL,
    bullish_mentions INTEGER NOT NULL,
    bearish_mentions INTEGER NOT NULL,
    neutral_mentions INTEGER NOT NULL,
    unique_authors INTEGER NOT NULL,
    unique_threads INTEGER NOT NULL,
    source_diversity_score REAL NOT NULL,
    average_alpha_signal_score REAL NOT NULL,
    average_hype_adjusted_signal_score REAL NOT NULL,
    average_depth_score REAL NOT NULL,
    average_hype_score REAL NOT NULL,
    average_claim_specificity_score REAL NOT NULL,
    average_evidence_quality_numeric REAL NOT NULL,
    mention_growth_rate REAL,
    acceleration_score REAL NOT NULL,
    emerging_ticker_score REAL NOT NULL,
    low_mentions_high_signal INTEGER NOT NULL,
    new_ticker_detected INTEGER NOT NULL,
    PRIMARY KEY (analysis_run_id, ticker, time_bucket),
    FOREIGN KEY (analysis_run_id) REFERENCES analysis_runs(analysis_run_id)
);

CREATE TABLE IF NOT EXISTS ticker_consensus_cache (
    ticker TEXT NOT NULL,
    scope_key TEXT NOT NULL,
    model_name TEXT NOT NULL,
    ollama_url TEXT NOT NULL DEFAULT '',
    latest_run_id TEXT NOT NULL DEFAULT '',
    evidence_signature TEXT NOT NULL,
    summary_json TEXT NOT NULL DEFAULT '{}',
    classifier_mode TEXT NOT NULL DEFAULT '',
    evidence_item_ids TEXT NOT NULL DEFAULT '[]',
    generated_at TEXT NOT NULL,
    PRIMARY KEY (ticker, scope_key, model_name)
);

CREATE TABLE IF NOT EXISTS ticker_signal_events (
    signal_id TEXT PRIMARY KEY,
    ticker TEXT NOT NULL,
    company_name TEXT NOT NULL DEFAULT 'Unknown',
    signal_time TEXT NOT NULL,
    analysis_run_id TEXT,
    run_type TEXT NOT NULL,
    source_set_hash TEXT NOT NULL,
    signal_rank INTEGER NOT NULL DEFAULT 0,
    emerging_ticker_score REAL NOT NULL DEFAULT 0,
    adjusted_acceleration_score REAL NOT NULL DEFAULT 0,
    alpha_signal_score REAL NOT NULL DEFAULT 0,
    hype_score REAL NOT NULL DEFAULT 0,
    hype_adjusted_signal_score REAL NOT NULL DEFAULT 0,
    evidence_quality REAL NOT NULL DEFAULT 0,
    claim_specificity_score REAL NOT NULL DEFAULT 0,
    source_diversity REAL NOT NULL DEFAULT 0,
    controversy_score REAL NOT NULL DEFAULT 0,
    mention_rate REAL NOT NULL DEFAULT 0,
    thread_rate REAL NOT NULL DEFAULT 0,
    author_rate REAL NOT NULL DEFAULT 0,
    share_of_voice REAL,
    trend_reliability TEXT NOT NULL DEFAULT '',
    coverage_reliability REAL NOT NULL DEFAULT 0,
    top_evidence_item_ids TEXT NOT NULL DEFAULT '[]',
    top_evidence_titles TEXT NOT NULL DEFAULT '[]',
    top_evidence_excerpts TEXT NOT NULL DEFAULT '[]',
    scoring_version TEXT NOT NULL DEFAULT '',
    manual_signal INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    FOREIGN KEY (analysis_run_id) REFERENCES analysis_runs(analysis_run_id)
);

CREATE TABLE IF NOT EXISTS ticker_market_prices (
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    open REAL,
    high REAL,
    low REAL,
    close REAL,
    adjusted_close REAL,
    volume REAL,
    data_source TEXT NOT NULL DEFAULT 'yfinance',
    fetched_at TEXT NOT NULL,
    PRIMARY KEY (ticker, date)
);

CREATE TABLE IF NOT EXISTS ticker_signal_outcomes (
    signal_id TEXT PRIMARY KEY,
    ticker TEXT NOT NULL,
    signal_time TEXT NOT NULL,
    price_at_signal REAL,
    return_1d REAL,
    return_3d REAL,
    return_7d REAL,
    return_14d REAL,
    return_30d REAL,
    max_gain_7d REAL,
    max_gain_14d REAL,
    max_gain_30d REAL,
    max_drawdown_7d REAL,
    max_drawdown_14d REAL,
    max_drawdown_30d REAL,
    volume_spike_3d REAL,
    volume_spike_7d REAL,
    volume_spike_14d REAL,
    volume_spike_30d REAL,
    abnormal_volume_7d REAL,
    abnormal_volume_30d REAL,
    benchmark_return_7d REAL,
    benchmark_return_30d REAL,
    excess_return_7d REAL,
    excess_return_30d REAL,
    outcome_last_updated TEXT NOT NULL,
    FOREIGN KEY (signal_id) REFERENCES ticker_signal_events(signal_id)
);

CREATE TABLE IF NOT EXISTS ticker_signal_attention_outcomes (
    signal_id TEXT PRIMARY KEY,
    ticker TEXT NOT NULL,
    signal_time TEXT NOT NULL,
    future_mentions_7d INTEGER NOT NULL DEFAULT 0,
    future_mentions_14d INTEGER NOT NULL DEFAULT 0,
    future_mentions_30d INTEGER NOT NULL DEFAULT 0,
    future_unique_threads_7d INTEGER NOT NULL DEFAULT 0,
    future_unique_threads_14d INTEGER NOT NULL DEFAULT 0,
    future_unique_threads_30d INTEGER NOT NULL DEFAULT 0,
    future_unique_authors_7d INTEGER NOT NULL DEFAULT 0,
    future_unique_authors_14d INTEGER NOT NULL DEFAULT 0,
    future_unique_authors_30d INTEGER NOT NULL DEFAULT 0,
    future_source_count_7d INTEGER NOT NULL DEFAULT 0,
    future_source_count_14d INTEGER NOT NULL DEFAULT 0,
    future_source_count_30d INTEGER NOT NULL DEFAULT 0,
    future_share_of_voice_7d REAL,
    future_share_of_voice_14d REAL,
    future_share_of_voice_30d REAL,
    attention_spread_7d REAL,
    attention_spread_14d REAL,
    attention_spread_30d REAL,
    attention_outcome_reliability TEXT NOT NULL DEFAULT 'Low',
    outcome_last_updated TEXT NOT NULL,
    FOREIGN KEY (signal_id) REFERENCES ticker_signal_events(signal_id)
);

CREATE TABLE IF NOT EXISTS ticker_signal_labels (
    signal_id TEXT PRIMARY KEY,
    user_label TEXT NOT NULL,
    user_notes TEXT NOT NULL DEFAULT '',
    user_label_updated_at TEXT NOT NULL,
    FOREIGN KEY (signal_id) REFERENCES ticker_signal_events(signal_id)
);

CREATE TABLE IF NOT EXISTS ticker_signal_random_benchmarks (
    signal_id TEXT NOT NULL,
    benchmark_ticker TEXT NOT NULL,
    sample_index INTEGER NOT NULL,
    universe_name TEXT NOT NULL DEFAULT '',
    sample_seed TEXT NOT NULL DEFAULT '',
    signal_date TEXT NOT NULL,
    price_at_signal REAL,
    return_7d REAL,
    return_30d REAL,
    max_gain_7d REAL,
    max_drawdown_7d REAL,
    volume_spike_7d REAL,
    volume_spike_30d REAL,
    outcome_last_updated TEXT NOT NULL,
    PRIMARY KEY (signal_id, benchmark_ticker),
    FOREIGN KEY (signal_id) REFERENCES ticker_signal_events(signal_id)
);

CREATE INDEX IF NOT EXISTS idx_sources_active ON sources(active);
CREATE INDEX IF NOT EXISTS idx_runs_completed ON analysis_runs(completed_at);
CREATE INDEX IF NOT EXISTS idx_runs_type ON analysis_runs(run_type, canonical_trend_run);
CREATE INDEX IF NOT EXISTS idx_source_coverage_run ON scrape_source_coverage(analysis_run_id);
CREATE INDEX IF NOT EXISTS idx_mentions_run_time ON item_ticker_mentions(analysis_run_id, created_time);
CREATE INDEX IF NOT EXISTS idx_mentions_run_ticker ON item_ticker_mentions(analysis_run_id, ticker);
CREATE INDEX IF NOT EXISTS idx_buckets_run_ticker ON ticker_time_buckets(analysis_run_id, ticker);
CREATE INDEX IF NOT EXISTS idx_signal_events_ticker_time ON ticker_signal_events(ticker, signal_time DESC);
CREATE INDEX IF NOT EXISTS idx_signal_events_run ON ticker_signal_events(analysis_run_id, signal_time DESC);
CREATE INDEX IF NOT EXISTS idx_market_prices_ticker_date ON ticker_market_prices(ticker, date);
CREATE INDEX IF NOT EXISTS idx_signal_random_signal ON ticker_signal_random_benchmarks(signal_id);
