CREATE TABLE IF NOT EXISTS sources (
    source_id INTEGER PRIMARY KEY AUTOINCREMENT,
    source_key TEXT NOT NULL UNIQUE,
    source_type TEXT NOT NULL,
    display_name TEXT NOT NULL,
    normalized_value TEXT NOT NULL,
    url TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    date_added TEXT NOT NULL,
    notes TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS analysis_runs (
    analysis_run_id TEXT PRIMARY KEY,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    status TEXT NOT NULL,
    data_mode TEXT NOT NULL,
    selected_source_ids TEXT NOT NULL,
    time_window_label TEXT NOT NULL,
    time_window_start TEXT NOT NULL,
    time_window_end TEXT NOT NULL,
    max_posts_per_source INTEGER NOT NULL,
    max_comments_per_thread INTEGER NOT NULL,
    include_comments INTEGER NOT NULL,
    run_deeper_analysis INTEGER NOT NULL,
    ollama_model TEXT NOT NULL,
    ollama_url TEXT NOT NULL,
    summary_json TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS reddit_items (
    item_id TEXT PRIMARY KEY,
    source_id INTEGER,
    source_type TEXT NOT NULL,
    source_name TEXT NOT NULL,
    subreddit TEXT,
    thread_id TEXT NOT NULL,
    thread_title TEXT NOT NULL,
    thread_url TEXT NOT NULL,
    comment_id TEXT,
    parent_id TEXT,
    item_type TEXT NOT NULL,
    body_text TEXT NOT NULL,
    author TEXT NOT NULL,
    author_hash TEXT NOT NULL,
    score INTEGER NOT NULL,
    created_time TEXT NOT NULL,
    permalink TEXT NOT NULL,
    comment_depth INTEGER NOT NULL,
    raw_json TEXT NOT NULL,
    FOREIGN KEY (source_id) REFERENCES sources(source_id)
);

CREATE TABLE IF NOT EXISTS classifications (
    analysis_run_id TEXT NOT NULL,
    item_id TEXT NOT NULL,
    sentiment TEXT NOT NULL,
    confidence REAL NOT NULL,
    tickers TEXT NOT NULL,
    company_names TEXT NOT NULL,
    summary TEXT NOT NULL,
    bull_case TEXT NOT NULL,
    bear_case TEXT NOT NULL,
    evidence_quality TEXT NOT NULL,
    depth_score INTEGER NOT NULL,
    hype_score INTEGER NOT NULL,
    claim_specificity_score INTEGER NOT NULL,
    repetition_score INTEGER NOT NULL,
    needs_deeper_analysis INTEGER NOT NULL,
    red_flags TEXT NOT NULL,
    claims_to_verify TEXT NOT NULL,
    alpha_signal_score REAL NOT NULL,
    hype_adjusted_signal_score REAL NOT NULL,
    model_name TEXT NOT NULL,
    classifier_mode TEXT NOT NULL,
    deeper_analysis_json TEXT NOT NULL DEFAULT '{}',
    analyzed_at TEXT NOT NULL,
    PRIMARY KEY (analysis_run_id, item_id),
    FOREIGN KEY (analysis_run_id) REFERENCES analysis_runs(analysis_run_id),
    FOREIGN KEY (item_id) REFERENCES reddit_items(item_id)
);

CREATE TABLE IF NOT EXISTS item_ticker_mentions (
    analysis_run_id TEXT NOT NULL,
    item_id TEXT NOT NULL,
    source_id INTEGER,
    source_type TEXT NOT NULL,
    source_name TEXT NOT NULL,
    subreddit TEXT,
    thread_id TEXT NOT NULL,
    thread_title TEXT NOT NULL,
    comment_id TEXT,
    parent_id TEXT,
    author_hash TEXT NOT NULL,
    created_time TEXT NOT NULL,
    created_date TEXT NOT NULL,
    time_bucket TEXT NOT NULL,
    item_type TEXT NOT NULL,
    ticker TEXT NOT NULL,
    company_name TEXT NOT NULL,
    sentiment TEXT NOT NULL,
    sentiment_numeric REAL,
    confidence REAL NOT NULL,
    alpha_signal_score REAL NOT NULL,
    hype_adjusted_signal_score REAL NOT NULL,
    depth_score INTEGER NOT NULL,
    hype_score INTEGER NOT NULL,
    evidence_quality TEXT NOT NULL,
    evidence_quality_numeric INTEGER NOT NULL,
    claim_specificity_score INTEGER NOT NULL,
    source_diversity_score REAL NOT NULL,
    controversy_score REAL NOT NULL,
    repetition_score INTEGER NOT NULL,
    reddit_score INTEGER NOT NULL,
    comment_depth INTEGER NOT NULL,
    text_length INTEGER NOT NULL,
    word_count INTEGER NOT NULL,
    contains_link INTEGER NOT NULL,
    contains_numbers INTEGER NOT NULL,
    contains_financial_terms INTEGER NOT NULL,
    needs_deeper_analysis INTEGER NOT NULL,
    low_mentions_high_signal INTEGER NOT NULL,
    new_ticker_detected INTEGER NOT NULL,
    red_flag_count INTEGER NOT NULL,
    claims_to_verify TEXT NOT NULL,
    summary TEXT NOT NULL,
    bull_case TEXT NOT NULL,
    bear_case TEXT NOT NULL,
    red_flags TEXT NOT NULL,
    deeper_analysis_json TEXT NOT NULL,
    body_text TEXT NOT NULL,
    permalink TEXT NOT NULL,
    PRIMARY KEY (analysis_run_id, item_id, ticker),
    FOREIGN KEY (analysis_run_id) REFERENCES analysis_runs(analysis_run_id),
    FOREIGN KEY (item_id) REFERENCES reddit_items(item_id),
    FOREIGN KEY (source_id) REFERENCES sources(source_id)
);

CREATE TABLE IF NOT EXISTS ticker_summaries (
    analysis_run_id TEXT NOT NULL,
    ticker TEXT NOT NULL,
    company_name TEXT NOT NULL,
    total_mentions INTEGER NOT NULL,
    bullish_mentions INTEGER NOT NULL,
    bearish_mentions INTEGER NOT NULL,
    neutral_mentions INTEGER NOT NULL,
    bullish_ratio REAL NOT NULL,
    bearish_ratio REAL NOT NULL,
    net_sentiment_score REAL,
    average_confidence REAL NOT NULL,
    average_alpha_signal_score REAL NOT NULL,
    average_hype_adjusted_signal_score REAL NOT NULL,
    average_depth_score REAL NOT NULL,
    average_hype_score REAL NOT NULL,
    average_claim_specificity_score REAL NOT NULL,
    average_evidence_quality_numeric REAL NOT NULL,
    source_diversity_score REAL NOT NULL,
    controversy_score REAL NOT NULL,
    repetition_score REAL NOT NULL,
    unique_authors INTEGER NOT NULL,
    unique_threads INTEGER NOT NULL,
    first_seen_date TEXT NOT NULL,
    most_recent_seen_date TEXT NOT NULL,
    mentions_this_period INTEGER NOT NULL,
    mentions_previous_period INTEGER NOT NULL,
    mention_change INTEGER NOT NULL,
    mention_growth_rate REAL,
    bullish_change INTEGER NOT NULL,
    bullish_growth_rate REAL,
    unique_author_growth INTEGER NOT NULL,
    unique_thread_growth INTEGER NOT NULL,
    rolling_mention_average REAL NOT NULL,
    acceleration_score REAL NOT NULL,
    emerging_ticker_score REAL NOT NULL,
    low_mentions_high_signal INTEGER NOT NULL,
    new_ticker_detected INTEGER NOT NULL,
    mega_popularity_penalty REAL NOT NULL,
    PRIMARY KEY (analysis_run_id, ticker),
    FOREIGN KEY (analysis_run_id) REFERENCES analysis_runs(analysis_run_id)
);

CREATE TABLE IF NOT EXISTS ticker_time_buckets (
    analysis_run_id TEXT NOT NULL,
    ticker TEXT NOT NULL,
    company_name TEXT NOT NULL,
    time_bucket TEXT NOT NULL,
    bucket_start TEXT NOT NULL,
    bucket_end TEXT NOT NULL,
    total_mentions INTEGER NOT NULL,
    bullish_mentions INTEGER NOT NULL,
    bearish_mentions INTEGER NOT NULL,
    neutral_mentions INTEGER NOT NULL,
    unique_authors INTEGER NOT NULL,
    unique_threads INTEGER NOT NULL,
    source_diversity_score REAL NOT NULL,
    average_alpha_signal_score REAL NOT NULL,
    average_hype_adjusted_signal_score REAL NOT NULL,
    average_depth_score REAL NOT NULL,
    average_hype_score REAL NOT NULL,
    average_claim_specificity_score REAL NOT NULL,
    average_evidence_quality_numeric REAL NOT NULL,
    mention_growth_rate REAL,
    acceleration_score REAL NOT NULL,
    emerging_ticker_score REAL NOT NULL,
    low_mentions_high_signal INTEGER NOT NULL,
    new_ticker_detected INTEGER NOT NULL,
    PRIMARY KEY (analysis_run_id, ticker, time_bucket),
    FOREIGN KEY (analysis_run_id) REFERENCES analysis_runs(analysis_run_id)
);

CREATE INDEX IF NOT EXISTS idx_sources_active ON sources(active);
CREATE INDEX IF NOT EXISTS idx_runs_completed ON analysis_runs(completed_at);
CREATE INDEX IF NOT EXISTS idx_mentions_run_time ON item_ticker_mentions(analysis_run_id, created_time);
CREATE INDEX IF NOT EXISTS idx_mentions_run_ticker ON item_ticker_mentions(analysis_run_id, ticker);
CREATE INDEX IF NOT EXISTS idx_buckets_run_ticker ON ticker_time_buckets(analysis_run_id, ticker);
